sudo: false
language: node_js
# IF NOT EXISTS is mariadb-10+ only - https://mariadb.com/kb/en/mariadb/comment-syntax/
before_script:
  - mysql -e 'create database /*M!50701 IF NOT EXISTS */ test;'
node_js:
  - '0.8'
  - '0.10'
  - '0.12'
  - '4.2'
  - '5.1'

matrix:
    include:
        - addons:
             mariadb: 5.5
          node_js: '2.3'
        - addons:
             mariadb: 10.0
          node_js: '2.3'
        - addons:
             mariadb: 10.1
          node_js: '2.3'
        - addons:
             mariadb: 5.5
          node_js: '1.0'
        - addons:
             mariadb: 10.0
          node_js: '1.0'
        - addons:
             mariadb: 10.1
          node_js: '1.0'
